name: Teams Webhook Test
on:
  workflow_dispatch:
    inputs:
      title:
        description: "Card title"
        default: "✅ Teams webhook test"
      color:
        description: "Hex color (no #)"
        default: "2D7D46"
      simulate_failure:
        description: "Send a failure-style card"
        type: boolean
        default: false

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Post test card to Teams
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          TITLE: ${{ inputs.title }}
          COLOR: ${{ inputs.simulate_failure && 'D24D57' || inputs.color }}
          EMOJI: ${{ inputs.simulate_failure && '❌' || '✅' }}
          SUMMARY: ${{ inputs.simulate_failure && 'Teams failure test' || 'Teams webhook test' }}
        run: |
          set -euo pipefail
          if [ -z "${TEAMS_WEBHOOK_URL:-}" ]; then
            echo "Missing TEAMS_WEBHOOK_URL secret"; exit 1
          fi

          # Build JSON safely so quotes/newlines can't break it
          PAYLOAD=$(jq -n \
            --arg color   "$COLOR" \
            --arg summary "$SUMMARY" \
            --arg title   "$EMOJI $TITLE" \
            --arg repo    "$GITHUB_REPOSITORY" \
            --arg actor   "$GITHUB_ACTOR" \
            --arg url     "$RUN_URL" \
            '{
              "@type":"MessageCard",
              "@context":"https://schema.org/extensions",
              "themeColor": $color,
              "summary": $summary,
              "title": $title,
              "text": $summary,
              "sections": [
                {"facts":[
                  {"name":"Repo","value":$repo},
                  {"name":"Actor","value":$actor}
                ]}
              ],
              "potentialAction": [
                {"@type":"OpenUri","name":"View Run","targets":[{"os":"default","uri":$url}]}
              ]
            }')

          # Send and show response
          HTTP_CODE=$(curl -sS -o /tmp/teams_resp.txt -w "%{http_code}" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD" "$TEAMS_WEBHOOK_URL" || true)

          echo "HTTP $HTTP_CODE"
          echo "Response:"
          cat /tmp/teams_resp.txt || true

          # Treat non-2xx as failure
          case "$HTTP_CODE" in
            2*) exit 0 ;;
            *) echo "Posting to Teams failed"; exit 1 ;;
          esac
