name: Teams Webhook Test
on:
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Post test card to Teams
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          if [ -z "$TEAMS_WEBHOOK_URL" ]; then
            echo "Missing TEAMS_WEBHOOK_URL secret"; exit 1
          fi
          curl -H "Content-Type: application/json" \
            -d '{"@type":"MessageCard","@context":"https://schema.org/extensions","themeColor":"2D7D46","summary":"Teams webhook test","title":"✅ Teams webhook test"}' \
            "$TEAMS_WEBHOOK_URL"
